### ISSUE TITLE
Creating parts of tutorial

### ISSUE THREAD

**Issue by dani-lbnl** [BIDS/ISVC2019#1]
1) Extend this https://github.com/scikit-image/skimage-tutorials/blob/master/lectures/three_dimensional_image_processing.ipynb
to cover item b) and c) and perhaps: wusem? multi-otsu?
- Alex

2) visualization, itk widgets, data reduction (item d e e)
- Dani

**Comment by alexdesiqueira** [comment]
Closed due to lots of material already :) Please feel free to reopen if necessary.
